package:
  name: whr
  version: 2.0.3

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - pybind11 >=2.10.0

  run:
    - python


test:
  imports:
    - whr
  source_files:
    - tests
  commands:
    - python tests/test_whr.py

about:
  summary: A Python interface incorporating a C++ implementation of the Whole History Rating algorithm
  license_file: LICENSE